Feature/menu registration api
SVTeamD/sample-backend pull request #8
Opened 2022-07-18 18:26 UTC by ChoiPilkyu

finish!!! menu_api
complete!
No update because we can not use this feature.
why? our customer is grandmother or grandfather. update feature is very tired.

결론: we don't have update feature.
ok?

2022-07-18 18:29 UTC, KKodiac requested changes
Request removing unnecessary

2022-07-18 18:29 UTC, KKodiac commented on backend/models/crud.py
>  #################추가###################################################################
Please remove unnecessary comments😀

2022-07-18 18:29 UTC, KKodiac commented on backend/models/schemas.py
>  ###############추가
😀

2022-07-19 02:46 UTC, edi54 approved these changes
수고하셨습니다!!

2022-07-19 04:05 UTC, juwon5272 commented
고생하셨어요

2022-07-19 05:45 UTC, merged